// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Templatus command line")>]
[<assembly: GuidAttribute("1a2d4fdb-650e-48c5-abb8-a5348329811b")>]
[<assembly: AssemblyProductAttribute("Templatus")>]
[<assembly: AssemblyDescriptionAttribute("T4-like templating tool with support for F#")>]
[<assembly: AssemblyVersionAttribute("0.3.1")>]
[<assembly: AssemblyFileVersionAttribute("0.3.1")>]
[<assembly: AssemblyMetadataAttribute("githash","df84bacf1eb9133754c74bf9f23018c929fe26d0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Templatus command line"
    let [<Literal>] Guid = "1a2d4fdb-650e-48c5-abb8-a5348329811b"
    let [<Literal>] AssemblyProduct = "Templatus"
    let [<Literal>] AssemblyDescription = "T4-like templating tool with support for F#"
    let [<Literal>] AssemblyVersion = "0.3.1"
    let [<Literal>] AssemblyFileVersion = "0.3.1"
    let [<Literal>] AssemblyMetadata_githash = "df84bacf1eb9133754c74bf9f23018c929fe26d0"
