// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Templatus lib")>]
[<assembly: GuidAttribute("f4a3cb74-b623-4d17-a3d3-7861ca0513f8")>]
[<assembly: AssemblyProductAttribute("Templatus")>]
[<assembly: AssemblyDescriptionAttribute("T4-like templating tool with support for F#")>]
[<assembly: AssemblyVersionAttribute("0.3.1")>]
[<assembly: AssemblyFileVersionAttribute("0.3.1")>]
[<assembly: AssemblyMetadataAttribute("githash","df84bacf1eb9133754c74bf9f23018c929fe26d0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Templatus lib"
    let [<Literal>] Guid = "f4a3cb74-b623-4d17-a3d3-7861ca0513f8"
    let [<Literal>] AssemblyProduct = "Templatus"
    let [<Literal>] AssemblyDescription = "T4-like templating tool with support for F#"
    let [<Literal>] AssemblyVersion = "0.3.1"
    let [<Literal>] AssemblyFileVersion = "0.3.1"
    let [<Literal>] AssemblyMetadata_githash = "df84bacf1eb9133754c74bf9f23018c929fe26d0"
